/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import config.dbConnector;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author milan
 */
public class ViewMedicalRecordPet extends javax.swing.JFrame {
   private int currentUserId;

   
    /**
     * Creates new form ViewMedicalRecordPet
     */
   public ViewMedicalRecordPet(int currentUserId) {
    this.currentUserId = currentUserId;
    initComponents();
    viewMedicalRecordForUser(currentUserId);
}
  
    
  public void viewMedicalRecordForUser(int ownerId) {
   String[] columnNames = {
        "record_id", "appointment_id", "pet_name", "pet_breed",
        "pet_age", "diagnosis", "treatment", "prescription", "notes"
    };

    DefaultTableModel model = new DefaultTableModel(columnNames, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    tblUserRecords.setModel(model);

    // ✅ Correct SQL: no ambiguity, all fields properly selected
    String sql = "SELECT medicalrecord.record_id, " +
                 "medicalrecord.appointment_id, " +
                 "medicalrecord.pet_name, " +
                 "medicalrecord.pet_breed, " +
                 "medicalrecord.pet_age, " +
                 "medicalrecord.diagnosis, " +
                 "medicalrecord.treatment, " +
                 "medicalrecord.prescription, " +
                 "medicalrecord.notes " +
                 "FROM medicalrecord " +
                 "INNER JOIN appointment ON medicalrecord.appointment_id = appointment.appointment_id " +
                 "WHERE appointment.appointment_id = ?"; // ✅ THIS is the WHERE clause

    try (Connection con = new dbConnector().getConnection();
         PreparedStatement pst = con.prepareStatement(sql)) {

        pst.setInt(1, ownerId);

        ResultSet rs = pst.executeQuery();
        while (rs.next()) {
            Object[] row = {
                rs.getInt("record_id"),
                rs.getInt("appointment_id"),
                rs.getString("pet_name"),
                rs.getString("pet_breed"),
                rs.getString("pet_age"),
                rs.getString("diagnosis"),
                rs.getString("treatment"),
                rs.getString("prescription"),
                rs.getString("notes")
            };
            model.addRow(row);
        }

        rs.close();

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error loading medical records: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUserRecords = new javax.swing.JTable();
        cc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblUserRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Record ID", "Appointment ID", "Pet Name", "Pet Breed", "Pet Age", "Diagnosis", "Preciption", "Notes", "Treatment"
            }
        ));
        jScrollPane1.setViewportView(tblUserRecords);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, 730, 410));

        cc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cc.setText("Back");
        cc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccActionPerformed(evt);
            }
        });
        jPanel1.add(cc, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccActionPerformed
        userDashboard usf = new userDashboard();
        usf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ccActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMedicalRecordPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMedicalRecordPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMedicalRecordPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMedicalRecordPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUserRecords;
    // End of variables declaration//GEN-END:variables
}
